/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
        display: ['var(--font-display)'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        apple: {
          bg: 'var(--apple-bg)',
          'bg-secondary': 'var(--apple-bg-secondary)',
          surface: 'var(--apple-surface)',
          'surface-elevated': 'var(--apple-surface-elevated)',
          separator: 'var(--apple-separator)',
          text: 'var(--apple-text-primary)',
          'text-secondary': 'var(--apple-text-secondary)',
          'text-tertiary': 'var(--apple-text-tertiary)',
          blue: 'var(--apple-blue)',
          'blue-hover': 'var(--apple-blue-hover)',
          'blue-pastel': 'var(--apple-blue-pastel)',
          green: 'var(--apple-green)',
          'green-pastel': 'var(--apple-green-pastel)',
          orange: 'var(--apple-orange)',
          'orange-pastel': 'var(--apple-orange-pastel)',
          red: 'var(--apple-red)',
          'red-pastel': 'var(--apple-red-pastel)',
          yellow: 'var(--apple-yellow)',
          'yellow-pastel': 'var(--apple-yellow-pastel)',
          purple: 'var(--apple-purple)',
          'purple-pastel': 'var(--apple-purple-pastel)',
          pink: 'var(--apple-pink)',
          'pink-pastel': 'var(--apple-pink-pastel)',
          teal: 'var(--apple-teal)',
          'teal-pastel': 'var(--apple-teal-pastel)',
          indigo: 'var(--apple-indigo)',
          'indigo-pastel': 'var(--apple-indigo-pastel)',
        },
        notion: {
          bg: 'var(--notion-bg)',
          'bg-secondary': 'var(--notion-bg-secondary)',
          surface: 'var(--notion-surface)',
          'surface-hover': 'var(--notion-surface-hover)',
          'row-hover': 'var(--notion-row-hover)',
          'row-stripe': 'var(--notion-row-stripe)',
          border: 'var(--notion-border)',
          'border-strong': 'var(--notion-border-strong)',
          text: 'var(--notion-text-default)',
          'text-muted': 'var(--notion-text-muted)',
          'text-subtle': 'var(--notion-text-subtle)',
          'accent-blue': 'var(--notion-accent-blue)',
          'accent-blue-soft': 'var(--notion-accent-blue-soft)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'apple-sm': 'var(--apple-radius-sm)',
        'apple-md': 'var(--apple-radius-md)',
        'apple-lg': 'var(--apple-radius-lg)',
        'apple-xl': 'var(--apple-radius-xl)',
        'notion-sm': 'var(--notion-radius-sm)',
        'notion-md': 'var(--notion-radius-md)',
        'notion-lg': 'var(--notion-radius-lg)',
      },
      boxShadow: {
        'apple-sm': 'var(--apple-shadow-sm)',
        'apple-md': 'var(--apple-shadow-md)',
        'apple-lg': 'var(--apple-shadow-lg)',
        'apple-xl': 'var(--apple-shadow-xl)',
        'notion-sm': 'var(--notion-shadow-sm)',
        'notion-md': 'var(--notion-shadow-md)',
      },
      fontSize: {
        'display-sm': ['1.875rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'display-md': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.025em' }],
      },
      letterSpacing: {
        'apple-tight': '-0.02em',
      },
      transitionTimingFunction: {
        apple: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'skeleton-pulse': {
          '0%, 100%': { opacity: '0.55' },
          '50%': { opacity: '0.85' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'skeleton-pulse': 'skeleton-pulse 1.6s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
